### ISSUE TITLE
AnalogInputs as audio should be between -1 and 1

### ISSUE THREAD

**Issue by sensestage** [sensestage/supercollider#24]
Check if this happens right now.

**Comment by giuliomoro** [comment]
You'll need Bela's latest `dev` which includes support for the audio capelet which will do this for you.

**Comment by x37v** [comment]
I'm thinking that `AnalogIn`/`AnalogOut` could always be 0..1 and `SoundIn`/`Out` could do -1..1?

**Comment by x37v** [comment]
It looks like `Out.ar` expects *-1..1* and outputs that mapped to *0..5v* on the analog out or the full range as expected if you have the audio expander caplet, but `SoundIn.ar` maps the *0..4v* analog input or full range of the audio expander caplet to *0..1*.. should probably pick one or another.

**Comment by sensestage** [comment]
closed with #47
