### ISSUE TITLE
Occasionally getting "too many users"

### ISSUE THREAD

**Issue by giuliomoro** [sensestage/supercollider#30]
What does it mean?
Could it be correlated with #18 ?

**Comment by sensestage** [comment]
correlated to https://github.com/supercollider/supercollider/issues/1914

**Comment by giuliomoro** [comment]
Note that when I get "too many users",  scsynth will keep working.
Unlike the issue you reference, I DO NOT get 
`WARNING: Server localhost couldn't set client id to: 'too many users'`

but just 
`too many users`
and the program keeps running ok

**Comment by jreus** [comment]
I'm also getting this problem occasionally. Even when using the start-scsynth example:
`s.options.maxLogins = 64;  	   // set max number of clients
`
The problem happens after running s.startAliveThread; remotely, getting the warning:
```Receiving notification messages from server belaServer
WARNING: Client ID exceeds maxLogins. Some buses and buffers may overlap for remote server: belaServer
WARNING: Client ID exceeds maxLogins. Some buses and buffers may overlap for remote server: belaServer```

scsynth seems to continue working thereafter

**Comment by sensestage** [comment]
s.options.maxLogins should be set on both sides: both on the local and on the remote sclang.

I recommend using

s.options.maxLogins = 4;
