### ISSUE TITLE
`sclang` uses 80% CPU

### ISSUE THREAD

**Issue by giuliomoro** [sensestage/supercollider#34]
Just start it with a patch like [this](https://github.com/BelaPlatform/Bela/blob/master/examples/12-SuperCollider-EXPERIMENTAL/start-scsynth/_main.scd
) (i.e.: doing nothing) and - once `scsynth` has booted, you will get CPU usage around 80% for `sclang`.
It should not affect much the performance of the audio (as that runs at a higher priority), but it may affect, e.g.: the networking/OSC stuff?

* note that the CPU usage reported by `top` is as percentage where 100% corresponds to whatever has been left over from Xenomai (for instance if your audio is using 25% CPU, as reported by `cat /proc/xenomai/stat`, then 100% reported by `top`  will actually be `75%`).

**Comment by vivid-synth** [comment]
Looks like the same issue as https://github.com/supercollider/supercollider/issues/2144 . We'd really like to fix that but don't have a lot of people to look it over at the moment
