### ISSUE TITLE
Meta_Bus:audio: failed to get an audio bus allocated

### ISSUE THREAD

**Issue by jarmitage** [sensestage/supercollider#39]
I am trying to run [SuperDirt](https://github.com/musikinformatik/SuperDirt) on Bela

[This](https://gist.github.com/jarmitage/f4edf2131e15eb6d4b84daf53c9962c4) is my SuperCollider startup file

The code where SuperDirt calls Bus.audio is [here](https://github.com/musikinformatik/SuperDirt/blob/2280f8ec57dba9f2e012bccfbeed27390884337f/classes/SuperDirt.sc#L391)

On launch, this error prints 5-10 times: `Meta_Bus:audio: failed to get an audio bus allocated. numChannels: 2 server: localhost`

**Comment by telephon** [comment]
Have you tried `s.options.numAudioBusChannels = 1024` ?

**Comment by jarmitage** [comment]
That was it! Thanks

**Comment by telephon** [comment]
nice. Once you have worked it all out, it would be great to add to superdirt as a code snippet.
