### ISSUE TITLE
Add BelaScope UGen

### ISSUE THREAD

**Issue by sensestage** [sensestage/supercollider#6]

**Comment by giuliomoro** [comment]
@sensestage, if I got it right you suggested to add a method `logChannel(float value, int channel)`, and a method `frameCompleted()` to the Bela `Scope` class. Each `scopeChannel` uGen would call `Scope::logChannel()` while a sort of _"wrapping"_ ugen would then call `frameCompleted()`.

I thought over this and I think that we could do this, instead:
- we do not change the interface of Scope
-  the scopeChannel ugens "log" to the  _"wrapping"_ ugen, which stores in a buffer all the logged data for the current block. 
- when all the ugens have logged, the _"wrapping"_ ugen logs to Bela's `Scope` one frame at a time using the existing method `log(float* buffer)`.

Does it sound reasonable?

**Comment by elgiano** [comment]
Hello!
I just started using Bela, and really miss this feature when writing SC code. I would be happy to go for an implementation, here is how I would plan it, based on the discussion above. Please let me know what you think, it would be great to have some feedback before I start working on it

*Requirements:*
- Scope must be created on the server
- must be possible to scope to different channels from different synths
- use existing log() interface

*Implementation:*

**BelaScopeUGen:**
- init Scope object
- read maxChannels from belaScopeBus (\audio)
- copy to buffer

**BelaScope (sclang):**
init(server, maxChannels):
- reserve `belaScopeBus = Bus.audio(server, maxChannels)`
- add `{BelaScopeUGen.ar(belaScopeBus, maxChannels)}.play` to ServerTree, to tail (and possibly refuse to create more than one BelaScopeUGen)

scope(channel, data):
helper class method to be used in SynthDefs, returns `Out.ar(belaScopeBus+channel, data)`
  - data = data.asArray
  - if(channel + data.size > maxChannels): error
  - `data.collect: switch(d.rate){ \scalar }{ DC.ar(d) }{ \control }{ K2A.ar(d) }{ d }`

**Comment by giuliomoro** [comment]
Closed with a slightly different approach in 2fc8ce657613a24b5cecc5abe1776b5377af4bc6  a04483c9de5848657f361e858bf6261b02a0813d#75
