### ISSUE TITLE
Nicely handle different channel counts for I/O.

### ISSUE THREAD

**Issue by giuliomoro** [sensestage/supercollider#66]

**Comment by sensestage** [comment]
ah, this was one of the things that wasn't there yet in the initial implementation?
Should be fairly straightforward to adapt.

**Comment by giuliomoro** [comment]
actually, forgot to mention: this got fixed at some point for analogs, and here (giuliomoro/supercollider@1378ce7b8fab5467c7aef870105d02648918e638) for audio. Also, the current base branch for development is https://github.com/giuliomoro/supercollider/tree/bela/3.10-squashed , where I squashed most of the old commits to make it easy to rebase on top of upstream. I am awaiting the official release of upstream 3.10 before I get rid of all these branches, but it seems like it's dragging on forever.

**Comment by giuliomoro** [comment]
so yeah, 3.10 just came out this morning. Great timing!
