### ISSUE TITLE
Analog I/O as audio in/out should use range between -1 and 1 instead of 0 and 1

### ISSUE THREAD

**Issue by sensestage** [sensestage/supercollider#7]

**Comment by LFSaw** [comment]
```
AnalogInput : UGen {
    signalRange { ^\unipolar }
}
```

**Comment by sensestage** [comment]
No, you are referring to the AnalogInput UGen; the fix is needed in the Audio Driver backend for when the Analog I/O are used as audio channels rather than UGen-accessed analog I/O.

**Comment by sensestage** [comment]
But maybe the unipolar flag is useful to have in the Bela UGens.

**Comment by sensestage** [comment]
Added the unipolar info in 29be0ed1499ad0d05ff672c5117132688eeff85e

**Comment by sensestage** [comment]
Fixed via b7a2ba7d751c0db1095442efb3535a4035857278, thanks @giuliomoro!
