### ISSUE TITLE
Zero documentation for DigitalIn / AnalogIn

### ISSUE THREAD

**Issue by yratof** [sensestage/supercollider#70]
I've searched high and low and there is simply not enough documentation about DigitalIn and AnalogIn.

Trying to use these within a project, but at every stage finding errors.

Will there be documentation for these ugens?

**Comment by sensestage** [comment]
What kind of documentation are you looking for?
There are helpfiles available (which would need to be viewed on your laptop) and there are examples available.

**Comment by giuliomoro** [comment]
all help is available [here](https://github.com/supercollider/supercollider/tree/develop/HelpSource/Classes)

**Comment by yratof** [comment]
Lovely stuff @giuliomoro, thanks for following this up
